Updated build files

diff --git a/.github/workflows/packer-validate.yml b/.github/workflows/packer-validate.yml
--- a/.github/workflows/packer-validate.yml
+++ b/.github/workflows/packer-validate.yml
@@ -31,9 +31,21 @@ jobs:
       - name: Ensure `setup.sh` Exists in `scripts/` Folder
         run: |
           if [ ! -f scripts/setup.sh ]; then
-            echo "Error: scripts/setup.sh file is missing!"
+            echo "ERROR: scripts/setup.sh file is missing!"
             exit 1
           fi
+
+      - name: Create WebApp Zip File
+        run: |
+          zip -r webapp-demo.zip . || echo "ERROR: Failed to create webapp-demo.zip!" && exit 1
+
+      - name: Debug - Check WebApp Zip File
+        run: |
+          if [ ! -f webapp-demo.zip ]; then
+            echo "ERROR: webapp-demo.zip file is missing!"
+            exit 1
+          fi
+          ls -al
 
       - name: Install Packer
         uses: hashicorp/setup-packer@v2
