BUILD CI

diff --git a/.github/workflows/packer-build.yml b/.github/workflows/packer-build.yml
--- a/.github/workflows/packer-build.yml
+++ b/.github/workflows/packer-build.yml
@@ -49,7 +49,12 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
+
+        working-directory: ./packer # Ensure the script runs inside the correct directory
         run: |
+          echo "Checking if img-creation.pkr.hcl exists in packer directory..."
+          ls -l img-creation.pkr.hcl || { echo "Error: img-creation.pkr.hcl not found"; exit 1; }
+
           packer build \
           -var "aws_region=$AWS_DEFAULT_REGION" \
           -var "subnet_id=${{ secrets.SUBNET_ID }}" \
