Build packer

diff --git a/.github/workflows/packer-build.yml b/.github/workflows/packer-build.yml
--- a/.github/workflows/packer-build.yml
+++ b/.github/workflows/packer-build.yml
@@ -9,6 +9,21 @@ jobs:
     name: packer-build
     runs-on: ubuntu-latest
 
+    services:
+      mysql:
+        image: mysql:8.0
+        env:
+          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
+          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
+
+        ports:
+          - 3306:3306
+        options: >-
+          --health-cmd="mysqladmin ping --silent"
+          --health-interval=10s
+          --health-timeout=5s
+          --health-retries=3
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -44,24 +59,24 @@ jobs:
           packer init .
           packer fmt -recursive .
 
-      # - name: Configure AWS Credentials
+      - name: Configure AWS Credentials
 
-      #   working-directory: ./packer
-      #   run: |
-      #     echo "Checking if img-creation.pkr.hcl exists in packer directory..."
-      #     ls -l img-creation.pkr.hcl || { echo "Error: img-creation.pkr.hcl not found"; exit 1; }
+        working-directory: ./packer
+        run: |
+          echo "Checking if img-creation.pkr.hcl exists in packer directory..."
+          ls -l img-creation.pkr.hcl || { echo "Error: img-creation.pkr.hcl not found"; exit 1; }
 
-      #     packer build \
-      #     -var "aws_region=$AWS_DEFAULT_REGION" \
-      #     -var "access_key=${{ secrets.aws_access_key }}" \
-      #     -var "secret_key=${{ secrets.aws_secret_key }}" \}
-      #     -var "subnet_id=${{ secrets.SUBNET_ID }}" \
-      #     -var "source_ami=${{ secrets.SOURCE_AMI }}" \
-      #     -var "dev_user=${{ secrets.DEV_USER }}" \
-      #     -var "demo_user=${{ secrets.DEMO_USER }}" \
-      #     -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
-      #     -var "vpc_id=${{ secrets.VPC_ID }}" \
-      #     img-creation.pkr.hcl
+          packer build \
+          -var "aws_region=${{secrets.AWS_REGION}}" \
+          -var "access_key=${{ secrets.aws_access_key }}" \
+          -var "secret_key=${{ secrets.aws_secret_key }}" \}
+          -var "subnet_id=${{ secrets.SUBNET_ID }}" \
+          -var "source_ami=${{ secrets.SOURCE_AMI }}" \
+          -var "dev_user=${{ secrets.DEV_USER }}" \
+          -var "demo_user=${{ secrets.DEMO_USER }}" \
+          -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
+          -var "vpc_id=${{ secrets.VPC_ID }}" \
+          img-creation.pkr.hcl
 
       # - name: Configure AWS Credentials
       #   # working-directory: ./packer
@@ -97,34 +112,6 @@ jobs:
       #     -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
       #     -var "vpc_id=${{ secrets.VPC_ID }}" \
       #     img-creation.pkr.hcl
-
-      - name: Create Packer Variable File
-        working-directory: ./packer
-        run: |
-          cat > variables.pkrvars.hcl <<EOF
-          aws_region = "${{ secrets.AWS_REGION }}"
-          access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
-          secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
-          subnet_id = "${{ secrets.SUBNET_ID }}"
-          source_ami = "${{ secrets.SOURCE_AMI }}"
-          dev_user = "${{ secrets.DEV_USER }}"
-          demo_user = "${{ secrets.DEMO_USER }}"
-          security_group_id = "${{ secrets.SECURITY_GROUP_ID }}"
-          vpc_id = "${{ secrets.VPC_ID }}"
-          db_username = "${{ secrets.DB_USERNAME }}"
-          db_password = "${{ secrets.DB_PASSWORD }}"
-          db_database = "${{ secrets.DB_DATABASE }}"
-          EOF
-
-      - name: Configure AWS Credentials
-        working-directory: ./packer
-        run: |
-          echo "Checking if img-creation.pkr.hcl exists in packer directory..."
-          ls -l img-creation.pkr.hcl || { echo "Error: img-creation.pkr.hcl not found"; exit 1; }
-
-          packer build \
-          -var-file=variables.pkrvars.hcl \
-          img-creation.pkr.hcl
 
       - name: Verify AMI Creation
         run: |
