Build packer

diff --git a/.github/workflows/packer-build.yml b/.github/workflows/packer-build.yml
--- a/.github/workflows/packer-build.yml
+++ b/.github/workflows/packer-build.yml
@@ -44,17 +44,35 @@ jobs:
           packer init .
           packer fmt -recursive .
 
-      - name: Configure AWS Credentials
+      # - name: Configure AWS Credentials
 
+      #   working-directory: ./packer
+      #   run: |
+      #     echo "Checking if img-creation.pkr.hcl exists in packer directory..."
+      #     ls -l img-creation.pkr.hcl || { echo "Error: img-creation.pkr.hcl not found"; exit 1; }
+
+      #     packer build \
+      #     -var "aws_region=$AWS_DEFAULT_REGION" \
+      #     -var "access_key=${{ secrets.aws_access_key }}" \
+      #     -var "secret_key=${{ secrets.aws_secret_key }}" \}
+      #     -var "subnet_id=${{ secrets.SUBNET_ID }}" \
+      #     -var "source_ami=${{ secrets.SOURCE_AMI }}" \
+      #     -var "dev_user=${{ secrets.DEV_USER }}" \
+      #     -var "demo_user=${{ secrets.DEMO_USER }}" \
+      #     -var "security_group_id=${{ secrets.SECURITY_GROUP_ID }}" \
+      #     -var "vpc_id=${{ secrets.VPC_ID }}" \
+      #     img-creation.pkr.hcl
+
+      - name: Configure AWS Credentials
         working-directory: ./packer
         run: |
           echo "Checking if img-creation.pkr.hcl exists in packer directory..."
           ls -l img-creation.pkr.hcl || { echo "Error: img-creation.pkr.hcl not found"; exit 1; }
 
           packer build \
-          -var "aws_region=$AWS_DEFAULT_REGION" \
-          -var "access_key=${{ secrets.aws_access_key }}" \
-          -var "secret_key=${{ secrets.aws_secret_key }}" \}
+          -var "aws_region=${{ secrets.AWS_REGION }}" \
+          -var "access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
+          -var "secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
           -var "subnet_id=${{ secrets.SUBNET_ID }}" \
           -var "source_ami=${{ secrets.SOURCE_AMI }}" \
           -var "dev_user=${{ secrets.DEV_USER }}" \
